[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["layers", "layout", "renderer", "state", "freya", "elements", "components", "hooks", "common", "processor", "testing"]

[features]
devtools = ["freya/devtools"]
x11 = ["freya/x11"]
wireframe = ["freya/wireframe"]

[dev-dependencies]
freya = { path = "./freya"}
dioxus-native-core-macro = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-rsx = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-native-core = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-core-macro = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-hooks = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-core = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
tokio = "1.23.0"
reqwest = {version = "0.11.13", features = ["json"] }
serde = "1.0.152"
tracing-subscriber = "0.2.25"

[profile.release]
lto = true
opt-level = 3
