[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["layers", "layout", "renderer", "state", "freya", "elements", "components", "hooks", "common", "processor", "testing"]

[features]
devtools = ["freya/devtools"]
x11 = ["freya/x11"]
wireframe = ["freya/wireframe"]

[dev-dependencies]
freya = { path = "./freya"}
dioxus = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes" }
dioxus-rsx = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes" }
dioxus-native-core = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes" }
dioxus-core-macro = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes" }
dioxus-hooks = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes" }
dioxus-core = { git = "https://github.com/Demonthos/dioxus", branch="fix-non-str-attributes", features = ["sync_attributes"] }
tokio = "1.17.0"
reqwest = {version = "0.11.12", features = ["json"] }
serde = "1.0.145"
tracing-subscriber = "0.2.0"

[profile.release]
lto = true
opt-level = 3
