[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["layers", "layout", "renderer", "state", "freya", "elements", "components", "hooks"]

[features]
x11 = ["freya/x11"]
wireframe = ["freya/wireframe"]

[dev-dependencies]
freya = { path = "./freya"}
dioxus = { git = "https://github.com/marc2332/dioxus", branch = "feat/attribute-value-any", features = ["macro", "hooks"]}
tokio = "1.17.0"
fermi = { git = "https://github.com/marc2332/dioxus", branch = "feat/attribute-value-any" }