[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["layout-engine", "renderer", "state", "trev", "elements-namespace"]

[features]
x11 = ["trev/x11"]
wireframe = ["trev/wireframe"]

[dev-dependencies]
trev = { path = "./trev"}
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["macro", "hooks"]}
tokio = "1.17.0"
elements-namespace = { path = "./elements-namespace"}