[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["layout-engine", "renderer", "state", "trev"]

[dev-dependencies]
trev = { path = "./trev"}
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
tokio = "1.17.0"