[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["layout", "renderer", "state", "freya", "elements", "components", "hooks", "common", "core", "testing"]

[features]
devtools = ["freya/devtools"]
wireframe = ["freya/wireframe"]

[dev-dependencies]
freya = { path = "./freya"}
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561" }
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561", features=["macro", "hooks", "hot-reload"]}
dioxus-rsx = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}
dioxus-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}
dioxus-hooks = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}
tokio = "1.23.0"
reqwest = {version = "0.11.13", features = ["json"] }
serde = "1.0.152"
tracing-subscriber = "0.2.25"
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", rev="bea16f151f3eb519ca8da3e3c20482d345067561"}

[profile.release]
lto = true
opt-level = 3
