[package]
name = "freya-layers"
version = "0.1.0"
edition = "2021"

[dependencies]
freya-node-state = { path = "../state", version = "0.1.0" }
dioxus-native-core = { git = "https://github.com/dioxuslabs/dioxus"  }
dioxus = { git = "https://github.com/dioxuslabs/dioxus"  }