[package]
name = "freya-layout"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-native-core = { git = "https://github.com/dioxuslabs/dioxus"  }
dioxus = { git = "https://github.com/dioxuslabs/dioxus"  }
freya-node-state = { path = "../state", version = "0.1.0" }
freya-layers = { path = "../layers", version = "0.1.0" }

[dev-dependencies]
dioxus-native-core-macro = { git = "https://github.com/dioxuslabs/dioxus"  }
dioxus-core = { git = "https://github.com/dioxuslabs/dioxus"  }
fxhash = "0.2.1"
anymap = "0.12.1"
lazy_static = "1.4.0"
