[package]
name = "freya-layout"
description = "Cross-platform GUI Library."
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Marc Espín <mespinsanz@gmail.com>"]
readme = "../readme.md"
homepage = "https://github.com/marc2332/freya"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "cross-platform", "dioxus", "skia", "graphics"]
categories = ["GUI"]

[dependencies]
dioxus-native-core = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus = { git = "https://github.com/Demonthos/dioxus", branch="realdom-generic-over-custom-types", features = ["macro", "hooks"]}
freya-common = { path = "../common", version = "0.1.0" }
freya-node-state = { path = "../state", version = "0.1.0" }
freya-layers = { path = "../layers", version = "0.1.0" }
tokio = { version = "1.23.0", features = ["sync", "rt-multi-thread", "time"] }
freya-elements = { path = "../elements", version = "0.1.0"}
skia-safe = { version = "0.56.1", features = ["textlayout"] }

[dev-dependencies]
dioxus-native-core-macro = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-rsx = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-native-core = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-core-macro = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-hooks = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
dioxus-core = { git = "https://github.com/Demonthos/dioxus", branch = "realdom-generic-over-custom-types"}
fxhash = "0.2.1"
anymap = "0.12.1"
lazy_static = "1.4.0"
freya-components ={ path = "../components"}
