[package]
name = "components"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/marc2332/dioxus" , branch = "patch-3" }
elements-namespace = { path = "../elements-namespace"}
state = { path = "../state"}
fermi = { git = "https://github.com/marc2332/dioxus", branch = "patch-3" }
hooks = { path = "../hooks"}