[package]
name = "freya-components"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus"  }
fermi = { git = "https://github.com/dioxuslabs/dioxus" }
freya-elements = { path = "../elements", version = "0.1.0" }
freya-node-state = { path = "../state", version = "0.1.0" }
freya-hooks = { path = "../hooks", version = "0.1.0" }