[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-html = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus" }
anymap = "0.12.1"
fxhash = "0.2.1"
skia-safe = { version = "*", features = ["gl"] }
elements-namespace = { path = "../elements-namespace"}