[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[features]
x11 = ["skia-safe/x11"]
wireframe = []

[dependencies]
gl = "*"
glutin = "*"
skia-safe = { version = "*", features = ["gl", "textlayout"] }
dioxus-core = { git = "https://github.com/marc2332/dioxus" , branch = "patch-3" }
dioxus-native-core = { git = "https://github.com/marc2332/dioxus" , branch = "patch-3" }
dioxus-html = { git = "https://github.com/marc2332/dioxus" , branch = "patch-3" }
layout-engine = { path = "../layout-engine"}
state = { path = "../state"}
enumset = "1.0.11"
layers-engine = { path = "../layers-engine"}