[package]
name = "freya-renderer"
version = "0.1.0"
edition = "2021"

[features]
x11 = ["skia-safe/x11"]
wireframe = []

[dependencies]
gl = "*"
glutin = "*"
skia-safe = { version = "*", features = ["gl", "textlayout"] }
dioxus-core = { git = "https://github.com/dioxuslabs/dioxus"  }
dioxus-native-core = { git = "https://github.com/dioxuslabs/dioxus"  }
dioxus-html = { git = "https://github.com/dioxuslabs/dioxus"  }
enumset = "1.0.11"
freya-layout = { path = "../layout", version = "0.1.0" }
freya-node-state = { path = "../state", version = "0.1.0" }
freya-layers = { path = "../layers", version = "0.1.0" }