[package]
name = "freya-hooks"
description = "Cross-platform GUI Library."
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Marc Espín <mespinsanz@gmail.com>"]
readme = "../readme.md"
homepage = "https://github.com/marc2332/freya"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "cross-platform", "dioxus", "skia", "graphics"]
categories = ["GUI"]

[dependencies]
dioxus-rsx = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
dioxus-native-core = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
dioxus-core-macro = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
dioxus-hooks = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
dioxus-core = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
tween = "2.0.0"
tokio = { version = "1.23.0" }
freya-elements = { path = "../elements", version = "0.1.0" }
uuid = { version =  "1.2.2", features = ["v4"]}
xi-rope = "0.3.0"
freya-node-state = { path = "../state", version = "0.1.0" }
freya-common = { path = "../common", version = "0.1.0" }
nokhwa = {version = "0.10.3", features = ["input-native"] }
bytes = "1.3.0"

[dev-dependencies]
dioxus = { git = "https://github.com/Demonthos/dioxus", branch = "desktop-hot-reload"}
freya = { path = "../freya"}
freya-testing = { path = "../testing"}
